### ISSUE TITLE
does not seem to intercept all methods

### ISSUE THREAD

**Issue by wumpz** [Ericsson/proxy#7]
Using your library I wanted to intercept all methods of an existing class. But this seems only to work work some not all methods. Are there any restrictions for the classes and methods used? 

By the way, I am not able to use the instance variant of your library: 

```java
with(myinstance).interceptAll(i -> ...)
```

This one results in a NPE. Using the class variant `with(myClass, constructorArguments)` works but does not intercept all the methods.

**Comment by Elisedlund-ericsson** [comment]
Hi 
do you have an example on what kind of method it not able to intercept? 
basically for **object** interception(Class interception has fewer limitations) cannot intercept a methods if its: final, private or static


Limitations
- Class Interception:
  –	Final methods.
  –	Final classes.

- Object interception (also has above limitations):
  –	Static methods.
  –	Private methods.
  –	Can’t handle public variable accesses.
  –	Makes it harder to debug with the eclipse debugger. 
  –	Access to a non dangerous constructor needed.
  –	Can’t behave polymorfically (which class interception does)

example showing difference between object interception and class interception:

      ```
        Interceptor printInterceptor = data -> {
            System.out.println(data.getMethodName());
            return data.invoke();
        };

        List<String> list = Proxy.with(new ArrayList<String>()).interceptAll(printInterceptor).get();
        list.add("");
        list.contains("");
        list.toString();
        list.clear();
        list.remove("");

        //prints:
        //        add
        //        contains
        //        toString
        //        clear
        //        remove

        // no polymorfical calls to indexOf() or similar

        List<String> list2 = Proxy.with(ArrayList.class).interceptAll(printInterceptor).get();
        list2.add("");
        list2.contains("");
        list2.toString();
        list2.clear();
        list2.remove("");
        //prints:
        //        add
        //        contains
        //        indexOf called by contains
        //        toString
        //        iterator called by toString
        //        clear
        //        remove
```
